### ISSUE TITLE
Implement event data model for raven 

### ISSUE THREAD

**Issue by welvin21** [rcltech/phoenix#45]

**Comment by 98sean98** [comment]
let phoenix handle `image_url` generation by saving it to S3

so I think a client application should send an image converted to base64 string, phoenix picks that up and sends it to S3, and obtains an `image_url` saved into database. to send back an `event` object, phoenix should query S3 for the image, then convert it to base64 string to be sent back to the client to render. I think this way any client application would not have to deal with any S3 api or any urls directly.

anyhow, we will have to set up an S3 instance though, or do we have one already

**Comment by welvin21** [comment]
> let phoenix handle `image_url` generation by saving it to S3
> 
> so I think a client application should send an image converted to base64 string, phoenix picks that up and sends it to S3, and obtains an `image_url` saved into database. to send back an `event` object, phoenix should query S3 for the image, then convert it to base64 string to be sent back to the client to render. I think this way any client application would not have to deal with any S3 api or any urls directly.
> 
> anyhow, we will have to set up an S3 instance though, or do we have one already

I put a very little code regarding this conversion on my latest commit, the problem i encountered was sending back the data to the client (since our datamodel doesn't have `image_base64` field, but we have to send it anyway. Probably you have an idea?
